site_name: EPILEPSY-RWE
site_description: "Epilepsy Real-World Evidence (RWE) Project Documentation"
theme:
  name: material
  logo: images/logo_option_1.png
  palette:
    primary: purple
    accent: purple
nav:
  - Home: index.md
  - New to RWE? Start Here: free-rwe-resources.md
  - Epilepsy OMOP Data Set: epilepsy-omop-data-set.md
  - STARDUSTT Approach: stardustt-approach.md
  - OMOP/OHDSI Resources: omop-ohdsi-resources.md
  - Select Publications: select-publications.md
  - Authors: authors.md
plugins:
  - search
markdown_extensions:
  - md_in_html     # enables Markdown inside HTML blocks (not required here, but handy)
  - attr_list      # lets you use { } attributes on images/elements
